# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: sudo apt-get install awscli

      - run:
          name: Upload to S3
          command: |
            VERSION=`cat VERSION`
            mkdir build
            zip -r build/timber-cloudwatch-logs-lambda-function-$VERSION.zip .
            aws s3 cp build/timber-cloudwatch-logs-lambda-function-$VERSION.zip s3://packages.timber.io/timber-cloudwatch-logs-lambda-function-$VERSION.zip
            aws s3 cp build/timber-cloudwatch-logs-lambda-function-$VERSION.zip s3://packages.timber.io/timber-cloudwatch-logs-lambda-function-latest.zip